### ISSUE TITLE
Serde deserialize enum from PascalCase String value

### ISSUE THREAD

**Issue by valentin-gauthier-geosiris** [geosiris-technologies/etptypes-rs#6]
This kind of code doesn't work : 
`let a: Result<EndpointCapabilityKind, _> = serde_json::from_str(r#""MaxWebSocketMessagePayloadSize""#)`
Because serde wants a camel_case value like : "max_web_socket_frame_payload_size". But in the capabality list (e.g. in RequestSession), it will be given in PascalCase.

Solutions : 
- (Maybe but should be tested) : Change the derive serde option `#[serde(rename_all = "camelCase")]` by :
    `#[serde(rename_all = "pascalCase")]`
- Create a function that take a &str or a String and returns the enum value;

**Comment by untereiner** [comment]
I think we should test the first solution

**Comment by valentin-gauthier-geosiris** [comment]
see. https://github.com/geosiris-technologies/etptypes-rs/pull/8
