### ISSUE TITLE
Make enum iterable to loop over values

### ISSUE THREAD

**Issue by valentin-gauthier-geosiris** [geosiris-technologies/etptypes-rs#7]
https://docs.rs/strum/latest/strum/derive.EnumIter.html

**Comment by untereiner** [comment]
Do you have a use case ?

**Comment by valentin-gauthier-geosiris** [comment]
When you recieve a RequestSession, the endpoint_capabilities is a keys/values.
To make a negotiation, we have to check if the key correspond to a "EndpointCapabilityKind", and if yes, we make a specific negotiation (take the min of the server and client values for this kind).
It would be interesting to loop over EndpointCapabilityKind enum key and check for each if the key (a String) equals to the String representation of the enum key. If yes, negotiate. If key is not a EndpointCapabilityKind, no negotiation.

This avoid creating a match with all EndpointCapabilityKind keys written by hand.
This allows to create a function like : "fn isEndpointCapabilityKind(String value) -> boolean "

**Comment by untereiner** [comment]
Ok then maybe implement the `intoIterator` trait should be enough ?

**Comment by valentin-gauthier-geosiris** [comment]
see. https://github.com/geosiris-technologies/etptypes-rs/pull/8
